### ISSUE TITLE
extensionが入れられなくなってる問題とcivitai helperの変更の提案

### ISSUE THREAD

**Issue by naka444** [Zuntan03/EasySdxlWebUi#1]
forgeで
set COMMANDLINE_ARGS=^
--styles-file ../styles.csv ^
--gradio-allowed-path .. ^
があるとextension　インストール時に　extension access disabled because of command line flags　が発生する
上のオプションを消すと正常に動作した

civitai helperは
[Stable-Diffusion-Webui-Civitai-Helper](https://github.com/blue-pen5805/Stable-Diffusion-Webui-Civitai-Helper)
[Stable-Diffusion-Webui-Civitai-Helper](https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper)
[Stable-Diffusion-Webui-Civitai-Helper](https://github.com/butaixianran/Stable-Diffusion-Webui-Civitai-Helper)
の3つがあり、今はblue-pen5805のが入れられている

blue-pen5805のは今現在、エラーが発生居ているがbutaixianranのモノは発生していないから

**Comment by Zuntan03** [comment]
3eb49a297471935531506e688d0ba0650119233d で対応しました。

COMMANDLINE_ARGS に `--listen` を付与する際に、`--enable-insecure-extension-access` も追加するようにしました。
これにより `extension access disabled because of command line flags` が発生しなくなるはずです。

CivitaiHelper は butaixianran にしています。

この対応にもし問題がありましたら、お知らせください。

**Comment by david419kr** [comment]
WebUI内から検索してDLできるCivitai Helperだと何か問題があるのでしょうか？( https://github.com/zixaphir/Stable-Diffusion-Webui-Civitai-Helper )

こちらは「model-keyword」のExtension( https://github.com/mix1009/model-keyword.git )と組み合わせると、CivitaiのTrigger wordsを自動で取得し、Loraの選択時に自動でTrigger Wordsを入力してくれるのですが、

こないだのEasySdxlWebUiの更新でbutaixianran版に変わってから、この「model-keywordと組み合わせるとCivitaiのTrigger Wordsを自動で取得し入力してくれる機能」が働きません。

アプデ後、手動でbutaixianran版のCivitai Helperを削除し、webuiのExtensionタブからダウンロードし直すと正常に作動するようになりました。今の所特に問題は起きていません。

**Comment by Zuntan03** [comment]
切り替えてみました。

**Comment by david419kr** [comment]
夜遅くお疲れ様です。想像以上に速い対応、ありがとうございます！
